config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :user
  validates_presence_of :dish, :description
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[edit update destroy]
  before_action :authenticate_user!, only: %i[edit create destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes(:user).order(id: :desc).all
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.js {}
      else
        format.js { render js: "alert(\"#{@recipe.errors.full_messages.join(',')}.\");" }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find_by(id: params[:id])
      redirect_to(root_path, alert: "This recipe isn't belong to you!") unless @recipe
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:dish, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'recipes/header' %>

    <% if flash[:notice] %>
      <br/>
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <br/>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <br/>

    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="ms-5 me-5 mb-3">
  <a class="btn btn-primary mb-3" data-bs-toggle="collapse" href="#newRecipe" role="button" aria-expanded="false" aria-controls="newRecipe">
      Add new recipe
  </a>
  <div class="collapse mb-3" id="newRecipe">
    <%= form_for :recipe, remote: true, html: { id: 'recipe-form' } do |f| %>
      <div class="form-group mb-3">
        <%= f.label :dish %>
        <%= f.text_field :dish, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid d-flex justify-content-between">
    <%= link_to 'Recipr', root_path, class: "navbar-brand" %>
    <div class="navbar-nav">
      <% if current_user %>
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%= link_to 'Change Password', edit_registration_path(:user), class: "nav-link" %>
      <% else %>
        <%= link_to 'Sign Up', new_registration_path(:user), class: "nav-link" %>
        <%= link_to 'Log In', new_session_path(:user), class: "nav-link" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/recipes/_recipe.html.erb
<div class="card text-dark bg-light border-dark ms-5 me-5 mb-3" id="recipe-<%= recipe.id %>">
  <div class="card-header">
    <span class="h5"><%= recipe.dish %></span><span> author: <%= recipe.user.email %></span>
  </div>
  <div class="card-body">
    <p class="card-text"><%= recipe.description %></p>
    <% if current_user && recipe.user == current_user %>
      <p class="d-flex justify-content-end">
        <%= link_to "Delete", recipe_path(recipe), method: :delete, remote: true, class: "btn btn-danger" %>
      </p>
    <% end %>
  </div>
</div>

app/views/recipes/create.js.erb
$("#recipe-list").prepend("<%=j render partial: 'recipe', locals: { recipe: @recipe } %>");
$("#recipe-form")[0].reset();

app/views/recipes/destroy.js.erb
$("#recipe-<%= @recipe.id %>").remove();
alert('Recipe was successfully destroyed.');

app/views/recipes/index.html.erb
<% if current_user %>
  <%= render partial: 'form' %>
<% end %>

<div id="recipe-list">
  <% @recipes.each do |recipe| %>
    <%= render partial: 'recipe', locals: { recipe: recipe } %>
  <% end %>
</div>